
#-------------------oooooOOOOO00000OOOOOooooo-------------------#
#                                                               #
#               IMRT photon beam in water phantom               #
#                   James Keal, 04-JUNE-2016                    #
#                                                               #
#-------------------oooooOOOOO00000OOOOOooooo-------------------#

#/control/execute mac/verbose.mac
/control/execute mac/visu.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    5.0 m
/gate/world/geometry/setYLength    5.0 m
/gate/world/geometry/setZLength    5.0 m
/gate/world/vis/setVisible 0

# Target Waterbox
/control/execute mac/target-CT.mac

# Linac with backup X, Y and MLC
/gate/geometry/setMaterialDatabase  data/PreciseMaterials.db
/control/execute                    mac/precise_Linac.mac
/control/execute                    mac/kill_box.mac

#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList            emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      patient 0.1 mm
/gate/physics/Electron/SetCutInRegion   patient 0.1 mm
/gate/physics/Positron/SetCutInRegion   patient 0.1 mm

/gate/physics/Gamma/SetCutInRegion      mylinac 10 mm
/gate/physics/Electron/SetCutInRegion   mylinac 10 mm
/gate/physics/Positron/SetCutInRegion   mylinac 10 mm

/gate/physics/displayCuts
/gate/physics/print                     output/physics.txt

#=====================================================
# DETECTORS
#=====================================================

/gate/actor/addActor                               SimulationStatisticActor stat
/gate/actor/stat/save                              output/output-stat.txt
/gate/actor/stat/saveEveryNSeconds                 10

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  output/output.mhd
/gate/actor/doseDistribution/attachTo              patient
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setVoxelSize          1.250 1.250 1.250 mm
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep true
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/saveEveryNSeconds     60

/gate/actor/addActor                               FluenceActor  fluenceDistribution
/gate/actor/fluenceDistribution/save               output/output-Fluence.mhd
/gate/actor/fluenceDistribution/attachTo           patient
/gate/actor/fluenceDistribution/setVoxelSize       1.250 1.250 1.250 mm
/gate/actor/fluenceDistribution/stepHitType        pre
/gate/actor/fluenceDistribution/enableScatter      true

/gate/run/initialize

#=====================================================
# START BEAMS
#=====================================================

/control/execute mac/TrueBeam_v2_6X.mac
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/application/readTimeSlicesIn data/precise_BeamSource.timeslices
/gate/application/setTotalNumberOfPrimaries 100000000

/gate/application/start
/gate/application/describe
