# -----------------------------------------------------
# BEAM LIMITING DEVICE X
# James Keal, 23-MAY-2016
# -----------------------------------------------------

/gate/mylinacGantry/daughters/name                  backupX
/gate/mylinacGantry/daughters/insert                box
/gate/backupX/setMaterial                           Air
/gate/backupX/geometry/setXLength                   500.0 mm
/gate/backupX/geometry/setYLength                   500.0 mm
/gate/backupX/geometry/setZLength                   78.0 mm
/gate/backupX/placement/setTranslation              0.0 0.0 -40.78 cm
/gate/backupX/placement/setRotationAxis             0 0 1
/gate/backupX/placement/setRotationAngle            90 deg
/gate/backupX/vis/setVisible                        0


# -----------------------------------------------------
# ss_boite colli backup X gauche
# -----------------------------------------------------

/gate/backupX/daughters/name                        backupX_1
/gate/backupX/daughters/insert                      box
/gate/backupX_1/setMaterial                         Air
/gate/backupX_1/geometry/setXLength                 135.0 mm
/gate/backupX_1/geometry/setYLength                 219.0 mm
/gate/backupX_1/geometry/setZLength                 78.0 mm

/gate/backupX_1/daughters/name                      backupX_1_Kill_Plane
/gate/backupX_1/daughters/insert                    box
/gate/backupX_1_Kill_Plane/setMaterial              Vacuum
/gate/backupX_1_Kill_Plane/geometry/setXLength      134.62 mm
/gate/backupX_1_Kill_Plane/geometry/setYLength      218.44 mm
/gate/backupX_1_Kill_Plane/geometry/setZLength      1 nm
/gate/backupX_1_Kill_Plane/placement/setTranslation 0.0 0.0 38.862 mm
/gate/backupX_1_Kill_Plane/vis/setColor             blue
/gate/backupX_1_Kill_Plane/vis/setVisible           1

/gate/backupX_1/daughters/name                      backupX_1_Leaf
/gate/backupX_1/daughters/insert                    box
/gate/backupX_1_Leaf/setMaterial                    AcceleratorCollimatorLeafMaterial
/gate/backupX_1_Leaf/geometry/setXLength            134.62 mm
/gate/backupX_1_Leaf/geometry/setYLength            218.44 mm
/gate/backupX_1_Leaf/geometry/setZLength            77.724 mm
/gate/backupX_1_Leaf/placement/setTranslation       0.0 0.0 0.0 mm
/gate/backupX_1_Leaf/vis/setColor                   magenta
/gate/backupX_1_Leaf/vis/setVisible                 1


# -----------------------------------------------------
# ss_boite colli backup X droite
# -----------------------------------------------------

/gate/backupX/daughters/name                        backupX_2
/gate/backupX/daughters/insert                      box
/gate/backupX_2/setMaterial                         Air
/gate/backupX_2/geometry/setXLength                 135.0 mm
/gate/backupX_2/geometry/setYLength                 219.0 mm
/gate/backupX_2/geometry/setZLength                 78.0 mm

/gate/backupX_2/daughters/name                      backupX_2_Kill_Plane
/gate/backupX_2/daughters/insert                    box
/gate/backupX_2_Kill_Plane/setMaterial              Vacuum
/gate/backupX_2_Kill_Plane/geometry/setXLength      134.62 mm
/gate/backupX_2_Kill_Plane/geometry/setYLength      218.44 mm
/gate/backupX_2_Kill_Plane/geometry/setZLength      1 nm
/gate/backupX_2_Kill_Plane/placement/setTranslation 0.0 0.0 38.862 mm
/gate/backupX_2_Kill_Plane/vis/setColor             blue
/gate/backupX_2_Kill_Plane/vis/setVisible           1

/gate/backupX_2/daughters/name                      backupX_2_Leaf
/gate/backupX_2/daughters/insert                    box
/gate/backupX_2_Leaf/setMaterial                    AcceleratorCollimatorLeafMaterial
/gate/backupX_2_Leaf/geometry/setXLength            134.62 mm
/gate/backupX_2_Leaf/geometry/setYLength            218.44 mm
/gate/backupX_2_Leaf/geometry/setZLength            77.724 mm
/gate/backupX_2_Leaf/placement/setTranslation       0.0 0.0 0.0 mm
/gate/backupX_2_Leaf/vis/setColor                   magenta
/gate/backupX_2_Leaf/vis/setVisible                 1


# -----------------------------------------------------
# Translation & Motion
# -----------------------------------------------------

/gate/backupX_1/moves/insert genericMove
/gate/backupX_1/genericMove/setPlacementsFilename data/precise_X_BLD1.placements

/gate/backupX_2/moves/insert genericMove
/gate/backupX_2/genericMove/setPlacementsFilename data/precise_X_BLD2.placements
