#=====================================================
# VISUALISATION

/vis/open                             OGLIQt
/vis/drawVolume
/vis/viewer/flush
/vis/viewer/set/viewpointThetaPhi     60 60
/vis/viewer/set/style                 surface
#/vis/viewer/set/background           white
#/vis/viewer/set/targetPoint          0 0 -20 cm
#/vis/viewer/zoomTo                   4
/tracking/storeTrajectory             1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction           accumulate
